name: Localize strings
on: [push]
jobs:
  localize:
    runs-on: ubuntu-latest
    steps:
      - name: Localize strings
        env:
          OPENAI_TOKEN: ${{ secrets.OPENAI_TOKEN }}
          LOCALES_PATH: ./locales
          MODEL: gpt-4
          MAIN_LOCALE: en
        uses: voloshinskii/localize-ai@v1

      - name: commit and push all changed files
        env:
          CI_COMMIT_MESSAGE: Localize new strings
          CI_COMMIT_AUTHOR: CI
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
